@module("@emotion/css") external injectGlobal: string => unit = "injectGlobal"
@module("@emotion/css") external css: string => string = "css"
@module("@emotion/css") external keyframes: string => string = "keyframes"
@module("@emotion/css") external cx: array<string> => string = "cx"
@module("@emotion/css") external cxOption: array<option<string>> => string = "cx"
